sudo: false
language: php

matrix:
    include:
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        - php: hhvm-3.12
          sudo: required
          dist: trusty
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
    fast_finish: true
    allow_failures:
        - php: 7.1
        - php: nightly
        - php: hhvm-3.12

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit -v -c phpunit.xml.dist
  - ./vendor/bin/phpmd src/ text phpmd.xml.dist

cache:
  directories:
    - $HOME/.composer/cache
